export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Listings',
    route: '/listings',
    description:
      'Structured profiles for clinics, studios, agencies, and regional operators—category, geography, and contact paths in one place.',
    contentType: 'listing',
    enabled: true,
  },
  {
    key: 'classified',
    label: 'Classifieds',
    route: '/classifieds',
    description: 'Short-form posts for roles, rentals, equipment, and time-sensitive local offers.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Insights',
    route: '/articles',
    description: 'Guides, interviews, and checklists for buyers and operators who already narrowed their shortlist.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'image',
    label: 'Images',
    route: '/images',
    description: 'Portfolio and campaign imagery when the visual story matters as much as the written summary.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Profiles',
    route: '/profile',
    description: 'Identity pages for founders, practice leads, and brand accounts tied to your listings.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Research shelves for links, tender references, and documents your team revisits often.',
    contentType: 'social',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Blog Commenting',
    route: '/blog',
    description: 'Threaded responses attached to articles for questions and follow-up discussion.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF Library',
    route: '/pdf',
    description: 'Downloadable menus, rate cards, policies, and technical PDFs next to your listings.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organizations',
    route: '/team',
    description: 'Company and collective pages when several listings roll up to one legal entity.',
    contentType: 'profile',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listings',
  classified: '/classifieds',
  article: '/articles',
  image: '/images',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
